### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by gitcomits** [ereborinkorppi/ot-harjoitustyo#1]
## Yleiset huomiot

Ohejlma toimii dokumentin kuvauksen mukaisesti. 

Eräs huomio tähän alkuun jonka varmaan olet huomannut, `Summa` ja `Kuvaus` laatikot tyhjentyvät virhe-ilmoituksen myötä. Vaikka virheilmoitus tulee voisi syötetty tieto jäädä ruutuihin, ainakin kuvauksen osalta. 

## Koodikatselmointi

Luokat olivat erittäin selkeitä ja ne olivat nimetty oikeanlaisesti sekä kuvaavasti. 
Se missä ei aivan ollut yhtäläistä rakennetta oli luokkien importit, osassa importteja luokan nimi oli kirjoitettu kokonaan pienillä kirjaimilla kun taas osassa importti oli sama kuin luokan nimi isoineen ja pienineen kirjaimineen.   
Tämän huomioin ainakin seuraavassa luokassa. 

	AddNewView (add_new_view.py)	

Tiedostossa budget_item_repository.py kohdistuu importti yhteen funktioon 

	`from database_connection import get_database_connection`

Olisiko ehkä parempi jos database_connection.py sisältäisi luokan johon importti kohdistuisi?

Luokassa `BudgetItemRepository` (budget_item_repository.py) luodaan luokkaolio itse luokan ulkopuoellla.

	budget_item_repository = BudgetItemRepository(get_database_connection())

Muuttujaa ei käytetä kyseisessä luokassa, jos tarkoitus on käyttää muuttujaa jossain toisessa luokassa tulisi se luoda sitä käyttävässä luokassa. 
 
Luokassa `BudgetService` (budget_service.py) on seuraavanlainen importti ja konstruktori:

`from repositories.budget_item_repository import (
    budget_item_repository as default_budget_item_repository
)`

`class BudgetService:`
    
    def __init__(
        self,
        budget_item_repository=default_budget_item_repository
    ):

        self._budget_item_repository = budget_item_repository
        self.incomes = 0
        self.expenses = 0`

Importissa `budget_item_repository` nimetään `default_budget_item_repository`
konstruktorin argumenteissa `default_budget_item_repository` arvo annetaan `budget_item_repository` muuttujalle
kun taas itse konstruktorissa `self._budget_item_repository` saa arvokseen `budget_item_repository`

Luokan muissa funktioissa käytetään ainoastaan `self._budget_item_repository` muuttujaa. 

Sekä importtia että konstruktoria voisi vähän siistiä:

`from repositories.budget_item_repository import budget_item_repository`

`class BudgetService:`
    
    def __init__(self):

        self._budget_item_repository = budget_item_repository
        self.incomes = 0
        self.expenses = 0

Ylläoleva ajaisi mielestäni saman asian, ehkä vähän helpommin hahmoteltavissa olevana.

Samassa tiedostossa luokan BudgetService ulkopouolella luodaan muuttuja

	`budget_service = BudgetService()`

Jos muuttuujaa käytetään muissa luokissa olisi se hyvä luoda niissä luokissa missä sille on tarvetta. 

Luokassa `AddNewView` (add_new_view.py)

Kutsutaan useampaa funktiota tyyliin 

	`heading = ttk.Label(master=self._frame, text="Lisää uusi:", font="Helvetica 14 bold")`
	
En tiedä onko tämä tkinterin ominaisuus mutta luettavuus parantuisi mielestäni jos funktion kutsussa ei määriteltäisi muuttujia.

Mielestäni koodin luettavuutta helpottaisi kun muuttuja saa arvon funktiosta jos funktion argumentit olisivat samalla rivillä.
Esimerkki `GUI` (qui.py) luokasta, mutta toistuu useammassa muussakin. 

`self._current_view = HomeView(`
              `self._root,`
              `self._handle_add_new`
        `)`

vs.

`self._current_view = HomeView(self._root, self._handle_add_new)`

Yllä oleva siis oma mielipiteeni, molemmat tavat toimivat ja tuskin kummastakaan vähennetään pisteitä pylintissä.

## Testit

Testit vaikuttavat kattavan aika hyvin eri luokat, tosin budget_service_test.py sisältää kaksi eri testiluokkaa.
Nämä voisi erotella omiin tiedostoihinsa ihan vain selkeyden kannalta. 

## Loppupäätelmä

Kaiken kaikkian ohjelma vaikuttaa lupaavalta ja tulee vielä paranemaan käyttäjäystävällisemmäksi kunhan loputkin dokumentoidut ominaisuudet implementoidaan siihen. Aikaa on vielä muutama viikko, näin ulkopuolisena näkisin tärkeimpänä tulojen ja menojen erittelyn ja sen jälkeen onkin helpohkoa luoda logiikka kuukausi tasolle.

**Comment by ereborinkorppi** [comment]
Kiitos erittäin asiallisesta ja kattavasta palautteesta. Katsotaan mitä kaikkea tässä vielä ehtiikään.
